[package]
name = "multi-asset-escrow"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = "5.1"
casper-types = "6.1"

[lib]
name = "multi_asset_escrow"
path = "src/lib.rs"
bench = false
doctest = false

[[bin]]
name = "multi-asset-escrow"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
