[package]
name = "insurance-pool"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = "5.1"
casper-types = "7.0"

[lib]
name = "insurance_pool"
path = "src/lib.rs"
bench = false
doctest = false

[[bin]]
name = "insurance-pool"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
